### PR TITLE
Legacy rails ruby

### PR DESCRIPTION
**Pull request by ragingdave**

### CODE REVIEW

**Comment by ragingdave** [comment]
didn't mean to open a PR here, just against my fork

**Comment by brendon** [comment]
No worries @ragingdave. `4.2` eh! Is it a big app or just no scope from the customer to upgrade?

Not 100% sure this code will work there as it uses some more recent arel stuff.

**Comment by ragingdave** [comment]
More small team and a lot to do.

I've actually got it mostly working but hung up on what seems to be a rails bug/feature where setting the position to the same position, old rails treats that as not changed but newer rails treats that as a change even if it's not technically.

**Comment by brendon** [comment]
Fair enough :) I would guess it's to do with perhaps a change in the way you need to signal to rails that the position has changed. We force it here: https://github.com/brendon/positioning/blob/ead38ac95cabca002a16b69a32afef3e9c36eb20/lib/positioning.rb#L42

Perhaps the method to signal a change is different in older rails?

**Comment by ragingdave** [comment]
I finally got all the tests to pass, only a handful of changes honestly to get it compatible, but I don't plan on trying to merge it back into your gem to have to maintain a rails 4.2 implementation.

Your note though about how to force it was the final piece. Rails 4.2 for some reason, would after calling that then assigning the value, would clear that it changed. So flipping it to assign the value then `column_will_change!` ended up being the ultimate fix.

So thanks for that and wish me luck lol!

**Comment by brendon** [comment]
Ah that's very interesting :) They must have an inline `if` in the newer version of their assignment code so that it never event attempts to set that flag if the condition is false. Previously maybe they always set it and relied on a calculation to either set true or false.

Definitely good luck! :) If you want to keep it maintained as a Rails 4.2 fork ongoing I could potentially link to it in the readme for those that want to use it.

**Comment by ragingdave** [comment]
I'm not sure I would take it that far, and also nobody should be on rails 4.2 to begin with (says the pot calling the kettle black)....but even so I wouldn't be able to properly maintain it time investment wise. as it is, I'm pulling it in as a specific branch, it doesn't test anything beyond ruby 2.7.8 and rails 4.2.x (which I'll likely tackle when I need rails 5 lol).

But anyways, Thanks again!

**Comment by brendon** [comment]
No worries man. Been there and done that. I thought I'd be forever on 2.3! Glad I went through to the pain though. My big project is on 6.1 at the moment. I have to say, the move from 4.2 onward isn't really all that bad. The code base really settled down after the Merb merger days and taking a good look at why we were using specific gems really helped remove a lot of extra code where we were only using just a small slice of it. You'll get there :D

**Pull request closed without merging**
