### PR TITLE
Remove Advisory lock

### PR DESCRIPTION
**Pull request by brendon**
This is in favour of scope locks or locking all the records in a table if no scope exists.

### CODE REVIEW

**Comment by brendon** [comment]
@fractaledmind, sorry this is a little out of the blue, but I wondered if you had any thoughts about why my sqlite tests might be deadlocking? I've had a go at integrating your gem but there still appears to be a problem. The problem test in particular is:

https://github.com/brendon/positioning/blob/25fcdca88d172d562aa11875913a791aad65a55c/test/test_positioning.rb#L31-L51

I'd love to keep sqlite as a compatible database for this gem but am getting close to dropping it as the ability to keep the list ordering clean is the primary purpose of this library :)

I frequently encountered your work on getting sqlite working well in production for Rails. Well done! :)

**Comment by fractaledmind** [comment]
Let me dig in tonight and get back to you.

**Comment by brendon** [comment]
Thanks @fractaledmind :D

**Comment by rossme** [comment]
Hi @brendon, I was running the tests earlier and I had to increase the pool size to 20 in `database.yml` which solved the issue for me. Not sure if that helps or not. I've used `acts_as_list` and this is a terrific improvement over that gem. Nice job.

**Comment by brendon** [comment]
Thanks @rossme, that doesn't seem to have helped in the CI environment. I feel like there's something different about it vs the Mac environment.

**Comment by brendon** [comment]
Thank you for your kind words too! :D

**Comment by brendon** [comment]
Managed to remove `default_transaction_mode: IMMEDIATE` also. Maybe the tests aren't robust enough though.

**Comment by brendon** [comment]
Also managed to remove the `activerecord-enhancedsqlite3-adapter` gem. Sqlite tests pass with or without the row locking (as expected). They fail for the other databases without the locking, I guess indicating that the sqlite connection pool only gives write access one at a time to each thread which is what the row locking does for other databases. Just conjecture on my part.

Has anyone tried these modifications in production?

**Comment by brendon** [comment]
I've merged this into `main` and will do a new minor release since there is a breaking change. Please get in touch if you notice any issues.

**Pull request merged**
